config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :posts, only: [:new, :create, :show, :destroy] do
    resources :comments, only: :create
  end
  get '/list' => 'posts#index', as: :list

  resources :users, only: [:create, :edit, :update]
  get '/signup' => 'users#new', as: :signup

  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: :logout

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  field :body, type: String
  field :commenter, type: String

  embedded_in :post

  def date_added
  	self.created_at.localtime.strftime("%-m/%-d/%Y | %l:%M %p")
  end

end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include Geocoder::Model::Mongoid
  field :coordinates, :type => Array
  field :address
  geocoded_by :address   # can also be an IP address
  after_validation :geocode         # auto-fetch coordinates
  geocoded_by :address, :skip_index => true

  field :type, type: String
  field :breed, type: String
  field :age, type: String
  field :gender, type: String
  field :price, type: Float
  field :description, type: String

  belongs_to :user
  embeds_many :comments

  mount_uploader :image, AvatarUploader

  def date_published
    self.created_at.localtime.strftime("%A, %B %-d, %Y at %l:%M %p")
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  field :name, type: String
  field :email, type: String
  field :phone_number, type: String
  field :password_digest, type: String
  attr_reader :password

  has_many :posts

  def password=(unencrypted_password)
    unless unencrypted_password.empty?
    @password = unencrypted_password
  	self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def authenticate(unencrypted_password)
  	if BCrypt::Password.new(self.password_digest) == unencrypted_password
  		return self
  	else
  		return false
  	end
  end

  validates :name, presence: true, on: :create
  validates :email, presence: true, uniqueness: { case_sensitve: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, on: :create
  validates :password, presence: true, length: { in: 6..20 }, confirmation: true, on: :create

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		post = Post.find(params[:post_id])
		post_comment = comment_params
		post_comment[:commenter] = current_user.name
		comment = post.comments.create(post_comment)
		redirect_to post_path(comment.post)
	end

	private

	def comment_params
		params.require(:comment).permit(:body)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
include PostsHelper

	def index
		@posts = Post.where(type: params[:type], gender: params[:gender], age: params[:age]).all
	end

	def new
		@post = Post.new
	end

	def create
		@post = current_user.posts.new(post_params)
		if @post.save
			redirect_to list_path({type: @post.type, gender: @post.gender, age: @post.age})
		else
			render "new"
		end
	end

	def show
		@post = Post.find(params[:id])
		@comment = Comment.new
		address = @post.address
		google_maps(address)
	end

	def destroy
		@post = Post.find(params[:id])
		if @post.destroy
			redirect_to list_path({type: @post.type, gender: @post.gender, age: @post.age})
		else
			redirect_to post_path(@post)
		end
	end

	private

	def post_params
		params.require(:post).permit(:type, :breed, :age, :gender, :price, :description, :image, :user, :coordinates, :address, :geocode)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		@user = User.find_by(email: params[:login][:email])
		if @user && @user.authenticate(params[:login][:password])
			session[:user_id] = @user.id.to_s
			redirect_to root_path
		else
			redirect_to login_path
		end
	end

	def destroy
		session.delete :user_id
		redirect_to root_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@posts = Post.all
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id.to_s
			redirect_to root_path
		else
			render :new
		end
	end

	def edit
		@user = current_user
	end

	def update
		@user = current_user
		if @user.update_attributes(user_params)
			redirect_to root_path
		else
			render :edit
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :phone_number, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def google_maps(address)
		address = address.gsub " ","+"
		map_api = ENV['GOOGLE_MAPS']
		@map = "https://www.google.com/maps/embed/v1/place?key=#{map_api}&q=#{address}"
	end

	def post_owner
		current_user == @post.user
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def logged_in?
		session[:user_id] != nil
	end	

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PetMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Bubblegum+Sans|Permanent+Marker|Open+Sans+Condensed:300|Courgette|Indie+Flower' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<div class="nav-border">
	<%= render "shared/menu" %>
</div>


<div class="col-md-5" id="list-section">
<div id="list-name">
<h1><%= params[:type] %></h1>
</div>
<div id="list-info">
<h3><%= params[:gender] %> & <%= params[:age] %></h3>
</div>
	<div id="img-window">
		<% @posts.each do |post| %>

				<%= image_tag post.image.url, :size => "360x280", :crop => :fill %>
			<div>
				Breed: <%= post.breed %>
			</div>

			<div>
			 	<% if logged_in? %>
				<%= link_to "More Info", post_path(post) %>
				<% end %>
				<% if logged_in? == false %>
				<%= link_to "More Info", login_path %>
				<% end %>
			</div>

		<% end %>
	</div>
</div>

app/views/posts/new.html.erb
<%= render "shared/menu" %>

<div id="addbackground">

<div class="row">
		
		<%= form_for @post do |f| %>
			<div class="col-md-5 col-md-offset-1">
			<h1>Add a pet</h1>
			<h3>Include information about the pet to potential buyers</h3>
				<div class="form-group">
					<%= f.label :type, "Type:", class: "control-label" %>
					<%= f.select :type, TYPES, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :gender, "Gender:", class: "control-label" %>
					<%= f.select :gender, GENDERS, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :age, "Age:", class: "control-label" %>
					<%= f.select :age, AGES, class: "form-control" %>
				</div>
				<div class="form-group">	
					<%= f.label :breed, "Breed:", class: "control-label" %>
					<%= f.text_field :breed, placeholder: "ex. Golden Retriever", class: "form-control" %>
				</div>
				<div class="form-group">	
					<%= f.label :address, "Address:", class: "control-label" %>
					<%= f.text_field :address, class: "form-control" %>
				</div>
				<div class="input-prepend input-append">
					<span class="add-on">$</span>
					<%= f.text_field :price, class: "span2" %>
					<span class="add-on">.00</span>
				</div>
				<div class="form-group">
					<%= f.label :image, "Image:", class: "control-label" %>
					<%= f.file_field :image %>
				</div>
			</div>
			</br>
			<div class="col-md-5">
				<h4>Additional Information</h4>
				<div class="form-group">
					<%= f.text_area :description, class: "form-control input-lg" %>
				</div>
					<%= f.submit "Post this pet", class: "btn btn-primary" %>
			</div>

		<% end %>
</div>

app/views/posts/show.html.erb
<div class="nav-border">
	<%= render "shared/menu" %>
</div>

<div class="container-fluid">
<div class="row">
	<div class="col-md-5 col-md-offset-2">
		<h1><%= @post.breed %></h1>
		<h6>Posted on: <%= @post.date_published %> <% if post_owner %>
			<%= link_to "Delete my post", post_path(@post), method: :delete %>
			<% end %></h6>
		<div id="show-img">
		<%= image_tag @post.image.url, :size => "450x304", :crop => :fill %>
		</div>
	</div>

<div class="col-md-4">
	<div id="contact">
		<h3>Contact Owner</h3>
		<p><%= @post.user["name"] %></p>
		<p><%= @post.user["email"] %></p>
		<p><%= @post.user["phone_number"] %></p>
	</div>

	<div id="price">
		<h3>Price</h3>
		<p>$ <%= @post.price %></p>
		<%= link_to "Back to list", list_path({type: @post.type, gender: @post.gender, age: @post.age}) %>
	</div>
</div>

</div>

<div class="row">
	<div class="col-md-5 col-md-offset-2">
		<h3>About</h3>
		<p><%= @post.description %></p>
	</div>

	<div class="col-md-3">
		<h3>Location</h3>
		<p><iframe src="<%= @map %>"></iframe></p>
	</div>
</div>

<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h4>Comments</h4>
		<% @post.comments.each do |comment| %>
		<p><%= comment.commenter %> - <%= comment.date_added %></p>
		<p><%= comment.body %></p>
		<% end %>
		<%= form_for [@post, @comment] do |f| %>

			<div>
				<%= f.text_area :body, class: "input-lg" %>
			</div>

			<%= f.submit "Comment", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>
</div>

app/views/shared/_menu.html.erb
<% if logged_in? %>
	<header>
		<h2 id="logo"><%= link_to "Pet Me", root_path %></h2>
		<nav id="nav-bar">
			<%= link_to "Post a pet!", new_post_path, class: "btn btn-success" %>
		<div>
			<%= link_to "My Account", edit_user_path(current_user) %>
		</div>
		<div>
			<%= link_to 'Log Out', logout_path, method: :delete %>
		</div>
		</nav>
	</header>
<% end %>

<% if logged_in? == false %>
	<header>
		<h2 id="logo"><%= link_to "Pet Me", root_path %></h2>
		<nav id="nav-bar">
			<%= link_to "Post a pet!", login_path, class: "btn btn-success" %>
		<div>
			<%= link_to "Sign Up", signup_path %>
		</div>
		<div>
			<%= link_to "Log In", login_path %>
		</div>
		</nav>
	</header>
<% end %>

app/views/static_pages/home.html.erb
<div class="container-fluid" id="main">
	<%= render "shared/menu" %>
	<div class="row">
		<div class="col-md-12">
			<section class="primary">
				<div id="search">
					<h1>Buy pets around your location</h1>
					<h3>Contact owners, see images, and choose your preference</h3>
					<%= form_tag(list_path, method: "get") do %>

						<%= select_tag "type", options_from_collection_for_select(TYPES, "to_s", "to_s") %>
						<%= select_tag "gender", options_from_collection_for_select(GENDERS, "to_s", "to_s") %>
						<%= select_tag "age", options_from_collection_for_select(AGES, "to_s", "to_s") %>
						<%= submit_tag "Submit", class: "btn btn-primary" %>

					<% end %>
				</div>
			</section>
		</div>
	</div>	
</div>

<div class="cotainer-fluid">
	<div class="row" id="secondary">
		<div class="col-md-6 col-md-offset-1">
			<h1 class="text-center">"Help find these pets a home"</h1>
			<h2 class="text-center">Lorem ipsum dolor sit amet</h2>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
		</div>

		<div class="col-md-2 house">
			<%= image_tag 'house.png', :size => "300x200" %>
		</div>
	</div>
</div>

<div class="container-fluid" id="iphone">
	<div class="row">
		<div class="col-md-3 col-md-offset-7">
			<h1>Pet Me</h1>
			<h2>Coming soon to your phone</h2>
		</div>
	</div>
</div>

<div class="container-fluid" id="cat">
 	<div class="row">
 		<div class="col-md-6">
 			<div id="cat-page">
	 			<h1>Make a difference</h1>
	 			<p>
		 			Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
				</p>
				<% if logged_in? %>
	 			<%= link_to "Post a pet!", new_post_path, class: "btn btn-success" %>
	 			<% end %>
	 			<% if logged_in? == false %>
	 			<%= link_to "Post a pet!", login_path, class: "btn btn-success" %>
	 			<% end %>
 			</div>
 		</div>
 	</div>
</div>




		

app/views/users/edit.html.erb
<div class="nav-black">
	<%= render "shared/menu" %>
</div>

<div class="snake">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			<div class="part">
			<h1 class="text-center">Account Information</h1>
			<%= form_for @user do |f| %>

				<div class="form-group">
					<%= f.label :name, class: "control-label" %>
					<%= f.text_field :name, class: "form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :email, class: "control-label"%>
					<%= f.text_field :email, class: "form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :phone_number, "Phone Number (Optional)", class: "control-label"%>
					<%= f.text_field :phone_number, class: "form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :password, class: "control-label" %>
					<%= f.password_field :password, class: "form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :password_confirmation, class: "control-label" %>
					<%= f.password_field :password_confirmation, class: "form-control" %>
				</div>

				<div>
					<%= f.submit "Update", class: "btn btn-primary" %>
				</div>

			<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div class="nav-black">
	<%= render "shared/menu" %>
</div>

<div class="snake">

	<div class="row">
		<div class="col-sm-4 col-sm-offset-4">
			<div>
				<ul class="list-group">
				  <% @user.errors.full_messages.each do |msg| %>
				    <li class="list-group-item list-group-item-danger"><%= msg %></li>
				  <% end %>
				</ul>
			</div>

			<div class="part">
			<h1 class="text-center">Sign Up</h1>

			<%= form_for @user do |f| %>

				<div class="form-group">
					<%= f.label :name, class: "control-label" %>
					<%= f.text_field :name, class: "form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :email, class: "control-label"%>
					<%= f.text_field :email, class: "form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :phone_number, "Phone Number (Optional)", class: "control-label"%>
					<%= f.text_field :phone_number, class: "form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :password, class: "control-label" %>
					<%= f.password_field :password, class: "form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :password_confirmation, class: "control-label" %>
					<%= f.password_field :password_confirmation, class: "form-control" %>
				</div>

				<div>
					<%= f.submit "Sign me up!", class: "btn btn-primary" %>
				</div>

			<% end %>
			</div>
		</div>
	</div>
</div>